- hosts: apache_web
  tasks:
    - name: "installing the httpd software"
      package:
        name: "httpd"
        state: present

    - name: "installing the php on the webserver"
      package:
        name: "php"
        state: present

    - name: "copying the content into webserver"
      copy:
        dest: "/var/www/html/index.php"
        src: "/home/ec2-user/index.php"

    - name: "Start services of the httpd"
      service:
        name: "httpd"
        state: started
        enabled: yes


                    
- hosts: 127.0.0.1
  tasks:
    - name: "Install HAProxy for the LoadBalancer"
      package:
        name: "haproxy"
        state: present

    - name: "Configure the loadbalancer"
      template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "/home/ec2-user/updated_haproxy.cfg"

    - name: "Start services of the loadBalancer"
      service:
        name: "haproxy"
        state: started
        enabled: yes
